### ISSUE TITLE
AOSP-hikey: failed to build the vendor.img with errors related to build_verity_metadata command

### ISSUE THREAD

**Issue by liuyq** [liuyq/android-issues#1]
https://ci.linaro.org/job/lkft-aosp/262/
```
[ 95% 106569/111775] Target vendor fs image: out/target/product/hikey/vendor.img
FAILED: out/target/product/hikey/vendor.img
/bin/bash -c "(mkdir -p out/target/product/hikey/vendor ) && (mkdir -p out/target/product/hikey/obj/PACKAGING/vendor_intermediates && rm -rf out/target/product/hikey/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"vendor_extfs_inode_count=2048\" >>  out/target/product/hikey/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"vendor_fs_type=ext4\" >>  out/target/product/hikey/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"vendor_journal_size=0\" >>  out/target/product/hikey/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"vendor_size=268435456\" >>  out/target/product/hikey/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"vendor_selinux_fc=out/target/product/hikey/obj/ETC/file_contexts.bin_intermediates/file_contexts.bin\" >>  out/target/product/hikey/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"building_vendor_image=true\" >>  out/target/product/hikey/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"ext_mkuserimg=mkuserimg_mke2fs\" >>  out/target/product/hikey/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"fs_type=ext4\" >>  out/target/product/hikey/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"extfs_sparse_flag=-s\" >>  out/target/product/hikey/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"erofs_sparse_flag=-s\" >>  out/target/product/hikey/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"squashfs_sparse_flag=-s\" >>  out/target/product/hikey/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"f2fs_sparse_flag=-S\" >>  out/target/product/hikey/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"boot_signer=false\" >>  out/target/product/hikey/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"verity=true\" >>  out/target/product/hikey/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"verity_key=build/make/target/product/security/verity\" >>  out/target/product/hikey/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"verity_signer_cmd=verity_signer\" >>  out/target/product/hikey/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"verity_fec=false\" >>  out/target/product/hikey/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"system_verity_block_device=/dev/block/platform/soc/f723d000.dwmmc0/by-name/system\" >>  out/target/product/hikey/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"vendor_verity_block_device=/dev/block/platform/soc/f723d000.dwmmc0/by-name/vendor\" >>  out/target/product/hikey/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"root_dir=out/target/product/hikey/root\" >>  out/target/product/hikey/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"skip_fsck=true\" >>  out/target/product/hikey/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (PATH=out/host/linux-x86/bin/:system/extras/ext4_utils/:\$PATH out/host/linux-x86/bin/build_image out/target/product/hikey/vendor out/target/product/hikey/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt out/target/product/hikey/vendor.img out/target/product/hikey/system ) && (size=\$(for i in out/target/product/hikey/vendor.img ; do stat -c \"%s\" \"\$i\" | tr -d '\\n'; echo +; done; echo 0); total=\$(( \$( echo \"\$size\" ) )); printname=\$(echo -n \"out/target/product/hikey/vendor.img \" | tr \" \" +); maxsize=\$((268435456)); if [ \"\$total\" -gt \"\$maxsize\" ]; then echo \"error: \$printname too large (\$total > \$maxsize)\"; false; elif [ \"\$total\" -gt \$((maxsize - 32768)) ]; then echo \"WARNING: \$printname approaching size limit (\$total now; limit \$maxsize)\"; fi )"
2022-04-13 14:09:08 - build_image.py - ERROR   : Failed to build out/target/product/hikey/vendor.img from out/target/product/hikey/vendor
Traceback (most recent call last):
  File "/home/liuyq/data/android/master/out/host/linux-x86/bin/build_image/internal/stdlib/runpy.py", line 196, in _run_module_as_main
  File "/home/liuyq/data/android/master/out/host/linux-x86/bin/build_image/internal/stdlib/runpy.py", line 86, in _run_code
  File "/home/liuyq/data/android/master/out/host/linux-x86/bin/build_image/__main__.py", line 12, in <module>
  File "/home/liuyq/data/android/master/out/host/linux-x86/bin/build_image/internal/stdlib/runpy.py", line 196, in _run_module_as_main
  File "/home/liuyq/data/android/master/out/host/linux-x86/bin/build_image/internal/stdlib/runpy.py", line 86, in _run_code
  File "/home/liuyq/data/android/master/out/host/linux-x86/bin/build_image/build_image.py", line 871, in <module>
  File "/home/liuyq/data/android/master/out/host/linux-x86/bin/build_image/build_image.py", line 863, in main
  File "/home/liuyq/data/android/master/out/host/linux-x86/bin/build_image/build_image.py", line 620, in BuildImage
  File "/home/liuyq/data/android/master/out/host/linux-x86/bin/build_image/verity_utils.py", line 335, in Build
  File "/home/liuyq/data/android/master/out/host/linux-x86/bin/build_image/verity_utils.py", line 116, in BuildVerityMetadata
  File "/home/liuyq/data/android/master/out/host/linux-x86/bin/build_image/common.py", line 314, in RunAndCheckOutput
common.ExternalError: Failed to run command '['build_verity_metadata', 'build', '266301440', '/home/liuyq/data/android/master/out/soong/.temp/tmpqrlgkssq_verity_images/verity_metadata.img', 'ef89c211a249a85dd8e4004b5c0a7275f5a60a32a3b960b1a46d705654070b21', 'aee087a5be3b982978c923f566a94613496b417f2af592639bc80d141e34dfe7', '/dev/block/platform/soc/f723d000.dwmmc0/by-name/vendor', 'verity_signer', 'build/make/target/product/security/verity.pk8']' (exit code 1):
Traceback (most recent call last):
  File "/home/liuyq/data/android/master/out/host/linux-x86/bin/build_verity_metadata/internal/stdlib/runpy.py", line 196, in _run_module_as_main
  File "/home/liuyq/data/android/master/out/host/linux-x86/bin/build_verity_metadata/internal/stdlib/runpy.py", line 86, in _run_code
  File "/home/liuyq/data/android/master/out/host/linux-x86/bin/build_verity_metadata/__main__.py", line 12, in <module>
  File "/home/liuyq/data/android/master/out/host/linux-x86/bin/build_verity_metadata/internal/stdlib/runpy.py", line 196, in _run_module_as_main
  File "/home/liuyq/data/android/master/out/host/linux-x86/bin/build_verity_metadata/internal/stdlib/runpy.py", line 86, in _run_code
  File "/home/liuyq/data/android/master/out/host/linux-x86/bin/build_verity_metadata/build_verity_metadata.py", line 114, in <module>
  File "/home/liuyq/data/android/master/out/host/linux-x86/bin/build_verity_metadata/build_verity_metadata.py", line 81, in build_verity_metadata
  File "/home/liuyq/data/android/master/out/host/linux-x86/bin/build_verity_metadata/build_verity_metadata.py", line 52, in sign_verity_table
  File "/home/liuyq/data/android/master/out/host/linux-x86/bin/build_verity_metadata/internal/stdlib/tempfile.py", line 483, in func_wrapper
TypeError: a bytes-like object is required, not 'str'

[ 95% 106570/111775] //external/conscrypt:conscrypt d8 [common apex29]
```

**Comment by liuyq** [comment]
needs to understand the settings here:
https://cs.android.com/android/platform/superproject/+/master:device/linaro/hikey/hikey.mk;l=6?q=PRODUCT_SUPPORTS_VERITY&ss=android%2Fplatform%2Fsuperproject
```
#setup dm-verity configs
PRODUCT_SYSTEM_VERITY_PARTITION := /dev/block/platform/soc/f723d000.dwmmc0/by-name/system
PRODUCT_VENDOR_VERITY_PARTITION := /dev/block/platform/soc/f723d000.dwmmc0/by-name/vendor
$(call inherit-product, build/target/product/verity.mk)
PRODUCT_SUPPORTS_BOOT_SIGNER := false
PRODUCT_SUPPORTS_VERITY_FEC := false
```
command to reproduce the error:
`PATH=out/host/linux-x86/bin/:system/extras/ext4_utils/:$PATH out/host/linux-x86/bin/build_image out/target/product/hikey/vendor out/target/product/hikey/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt out/target/product/hikey/vendor.img out/target/product/hikey/system `

content of file out/target/product/hikey/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt
```
vendor_extfs_inode_count=2048
vendor_fs_type=ext4
vendor_journal_size=0
vendor_size=268435456
vendor_selinux_fc=out/target/product/hikey/obj/ETC/file_contexts.bin_intermediates/file_contexts.bin
building_vendor_image=true
ext_mkuserimg=mkuserimg_mke2fs
fs_type=ext4
extfs_sparse_flag=-s
erofs_sparse_flag=-s
squashfs_sparse_flag=-s
f2fs_sparse_flag=-S
boot_signer=false
verity=true
verity_key=build/make/target/product/security/verity
verity_signer_cmd=verity_signer
verity_fec=false
system_verity_block_device=/dev/block/platform/soc/f723d000.dwmmc0/by-name/system
vendor_verity_block_device=/dev/block/platform/soc/f723d000.dwmmc0/by-name/vendor
root_dir=out/target/product/hikey/root
skip_fsck=true
```

**Comment by liuyq** [comment]
after disabled the verity settings, the content of file out/target/product/hikey/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt looks like this:
```
vendor_extfs_inode_count=2048
vendor_fs_type=ext4
vendor_journal_size=0
vendor_size=268435456
vendor_selinux_fc=out/target/product/hikey/obj/ETC/file_contexts.bin_intermediates/file_contexts.bin
building_vendor_image=true
ext_mkuserimg=mkuserimg_mke2fs
fs_type=ext4
extfs_sparse_flag=-s
erofs_sparse_flag=-s
squashfs_sparse_flag=-s
f2fs_sparse_flag=-S
root_dir=out/target/product/hikey/root
skip_fsck=true
```

**Comment by liuyq** [comment]
it is caused by the change here:
https://android-review.googlesource.com/c/platform/system/extras/+/2056529

and fixed with the change here:
https://android-review.googlesource.com/c/platform/system/extras/+/2064888

the write and read of tempfile with python3 deal with bytes instead of str, that needs to be updated for the conversion

https://docs.python.org/3/library/tempfile.html
