### ISSUE TITLE
AAPT_PARSER_FAILED|520050|DEPENDENCY_ISSUE 

### ISSUE THREAD

**Issue by liuyq** [liuyq/android-issues#21]
```
03-17 05:24:38 D/ModuleDefinition: Running module arm64-v8a CtsBluetoothTestCases
03-17 05:24:39 E/AaptParser: aapt2 dump badging stderr: W/ziparchive( 2239): Unable to open 'badging': No such file or directory
badging: error: No such file or directory.
03-17 05:24:39 E/AaptParser: Failed to run aapt2 on /lava-3936266/2/tests/2_cts-lkft/automated/android/noninteractive-tradefed/android-cts/tools/../../android-cts/testcases/CtsBluetoothTestCases.apk. stdout: 
03-17 05:24:39 E/ModuleDefinition: Unexpected Exception from preparer: com.android.tradefed.targetprep.suite.SuiteApkInstaller
03-17 05:24:39 E/ModuleDefinition: AaptParser failed for file CtsBluetoothTestCases.apk. The APK won't be installed [7A25756801BA7C0B hikey960:hikey960 SPM1.220819.019]
com.android.tradefed.targetprep.TargetSetupError[AAPT_PARSER_FAILED|520050|DEPENDENCY_ISSUE]: AaptParser failed for file CtsBluetoothTestCases.apk. The APK won't be installed [7A25756801BA7C0B hikey960:hikey960 SPM1.220819.019]
    at com.android.tradefed.targetprep.TestAppInstallSetup.parsePackageName(TestAppInstallSetup.java:739)
    at com.android.tradefed.targetprep.TestAppInstallSetup.resolveApkFiles(TestAppInstallSetup.java:625)
    at com.android.tradefed.targetprep.TestAppInstallSetup.setUp(TestAppInstallSetup.java:408)
    at com.android.tradefed.testtype.suite.ModuleDefinition.runPreparerSetup(ModuleDefinition.java:982)
    at com.android.tradefed.testtype.suite.ModuleDefinition.runTargetPreparation(ModuleDefinition.java:1415)
    at com.android.tradefed.testtype.suite.ModuleDefinition.runPreparation(ModuleDefinition.java:941)
    at com.android.tradefed.testtype.suite.ModuleDefinition.run(ModuleDefinition.java:476)
    at com.android.tradefed.testtype.suite.ITestSuite.runSingleModule(ITestSuite.java:926)
    at com.android.tradefed.testtype.suite.ITestSuite.run(ITestSuite.java:806)
    at com.android.tradefed.invoker.InvocationExecution.runTest(InvocationExecution.java:1335)
    at com.android.tradefed.invoker.InvocationExecution.runTests(InvocationExecution.java:1114)
    at com.android.tradefed.invoker.TestInvocation.prepareAndRun(TestInvocation.java:604)
    at com.android.tradefed.invoker.TestInvocation.performInvocation(TestInvocation.java:274)
    at com.android.tradefed.invoker.TestInvocation.invoke(TestInvocation.java:1322)
    at com.android.tradefed.command.CommandScheduler$InvocationThread.run(CommandScheduler.java:678)
03-17 05:24:39 E/ModuleDefinition: Some preparation step failed. failing the module arm64-v8a CtsBluetoothTestCases
```

**Comment by liuyq** [comment]
seems related to the commit here:
https://android-review.googlesource.com/c/platform/tools/tradefederation/+/2453907
only revert this change does not help, the cts still failed with other errors.

but if using the version built from AOSP Master tree, or new version aapt2 released by google maven, then it works.

**Comment by liuyq** [comment]
Like with the aapt2 from the following package, the problem will be gone away.
https://dl.google.com/android/maven2/com/android/tools/build/aapt2/7.4.2-8841542/aapt2-7.4.2-8841542-linux.jar
