### ISSUE TITLE
Android11-gsi-hikey960: ERROR:root:code for hash blake2b was not found

### ISSUE THREAD

**Issue by liuyq** [liuyq/android-issues#3]
https://ci.linaro.org/job/lkft-aosp/264/consoleFull
not sure what this error is, and if it affects the images generated
```
[ 78% 229/293] Target boot debug image: out/target/product/hikey960/boot-debug.img
ERROR:root:code for hash blake2b was not found.
Traceback (most recent call last):
  File "/data/android12/android11-gsi/out/host/linux-x86/bin/mkbootimg/internal/stdlib/hashlib.py", line 251, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/data/android12/android11-gsi/out/host/linux-x86/bin/mkbootimg/internal/stdlib/hashlib.py", line 120, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type blake2b
ERROR:root:code for hash blake2s was not found.
Traceback (most recent call last):
  File "/data/android12/android11-gsi/out/host/linux-x86/bin/mkbootimg/internal/stdlib/hashlib.py", line 251, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/data/android12/android11-gsi/out/host/linux-x86/bin/mkbootimg/internal/stdlib/hashlib.py", line 120, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type blake2s
ERROR:root:code for hash sha3_224 was not found.
Traceback (most recent call last):
  File "/data/android12/android11-gsi/out/host/linux-x86/bin/mkbootimg/internal/stdlib/hashlib.py", line 251, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/data/android12/android11-gsi/out/host/linux-x86/bin/mkbootimg/internal/stdlib/hashlib.py", line 120, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha3_224
ERROR:root:code for hash sha3_256 was not found.
Traceback (most recent call last):
  File "/data/android12/android11-gsi/out/host/linux-x86/bin/mkbootimg/internal/stdlib/hashlib.py", line 251, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/data/android12/android11-gsi/out/host/linux-x86/bin/mkbootimg/internal/stdlib/hashlib.py", line 120, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha3_256
ERROR:root:code for hash sha3_384 was not found.
Traceback (most recent call last):
  File "/data/android12/android11-gsi/out/host/linux-x86/bin/mkbootimg/internal/stdlib/hashlib.py", line 251, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/data/android12/android11-gsi/out/host/linux-x86/bin/mkbootimg/internal/stdlib/hashlib.py", line 120, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha3_384
ERROR:root:code for hash sha3_512 was not found.
Traceback (most recent call last):
  File "/data/android12/android11-gsi/out/host/linux-x86/bin/mkbootimg/internal/stdlib/hashlib.py", line 251, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/data/android12/android11-gsi/out/host/linux-x86/bin/mkbootimg/internal/stdlib/hashlib.py", line 120, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha3_512
ERROR:root:code for hash shake_128 was not found.
Traceback (most recent call last):
  File "/data/android12/android11-gsi/out/host/linux-x86/bin/mkbootimg/internal/stdlib/hashlib.py", line 251, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/data/android12/android11-gsi/out/host/linux-x86/bin/mkbootimg/internal/stdlib/hashlib.py", line 120, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type shake_128
ERROR:root:code for hash shake_256 was not found.
Traceback (most recent call last):
  File "/data/android12/android11-gsi/out/host/linux-x86/bin/mkbootimg/internal/stdlib/hashlib.py", line 251, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/data/android12/android11-gsi/out/host/linux-x86/bin/mkbootimg/internal/stdlib/hashlib.py", line 120, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type shake_256
[ 78% 230/293] build out/target/product/hikey960/obj/ETC/vendor_sepolicy.cil_intermediates/vendor_sepolicy.cil

```

**Comment by liuyq** [comment]
it could be fixed with the change here:
https://android-review.googlesource.com/c/platform/external/python/cpython3/+/2064952
